ALTER TABLE Teacher
    ADD COLUMN firstName VARCHAR,
    ADD COLUMN lastName VARCHAR,
    ADD COLUMN gender VARCHAR,
    ADD COLUMN dob VARCHAR,
    ADD COLUMN department VARCHAR,
    ADD COLUMN officeNumber VARCHAR;
